version: '3.9'

services:
  my-jenkins:
    image: my-jenkins
    build:
      context: .
    container_name: my-jenkins
    privileged: true
    restart: on-failure
    volumes:
      - jenkins-data:/var/jenkins_home
      # â†“ Host-Socket optional (kann bleiben oder entfernt werden)
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins-docker-certs:
  jenkins-data: